// src/constants/regionesComunasChile.js

// Mapa Región → Comunas (según listado que me enviaste)
export const REGIONES_COMUNAS = {
  "XV de Arica y Parinacota": [
    "Arica",
    "Camarones",
    "Putre",
    "General Lagos",
  ],

  "I de Tarapacá": [
    "Alto Hospicio",
    "Iquique",
    "Huara",
    "Camiña",
    "Colchane",
    "Pica",
    "Pozo Almonte",
  ],

  "II de Antofagasta": [
    "Tocopilla",
    "María Elena",
    "Calama",
    "Ollagüe",
    "San Pedro de Atacama",
    "Antofagasta",
    "Mejillones",
    "Sierra Gorda",
    "Taltal",
  ],

  "III de Atacama": [
    "Chañaral",
    "Diego de Almagro",
    "Copiapó",
    "Caldera",
    "Tierra Amarilla",
    "Vallenar",
    "Freirina",
    "Huasco",
    "Alto del Carmen",
  ],

  "IV de Coquimbo": [
    "La Serena",
    "La Higuera",
    "Coquimbo",
    "Andacollo",
    "Vicuña",
    "Paihuano",
    "Ovalle",
    "Río Hurtado",
    "Monte Patria",
    "Combarbalá",
    "Punitaqui",
    "Illapel",
    "Salamanca",
    "Los Vilos",
    "Canela",
  ],

  "V de Valparaíso": [
    "La Ligua",
    "Petorca",
    "Cabildo",
    "Zapallar",
    "Papudo",
    "Los Andes",
    "San Esteban",
    "Calle Larga",
    "Rinconada",
    "San Felipe",
    "Putaendo",
    "Santa María",
    "Panquehue",
    "Llaillay",
    "Catemu",
    "Quillota",
    "La Cruz",
    "Calera",
    "Nogales",
    "Hijuelas",
    "Limache",
    "Olmué",
    "Valparaíso",
    "Viña del Mar",
    "Quintero",
    "Puchuncaví",
    "Quilpué",
    "Villa Alemana",
    "Casablanca",
    "Concón",
    "Juan Fernández",
    "San Antonio",
    "Cartagena",
    "El Tabo",
    "El Quisco",
    "Algarrobo",
    "Santo Domingo",
    "Isla de Pascua",
  ],

  "VI del Libertador General Bernardo O'Higgins": [
    "Rancagua",
    "Graneros",
    "Mostazal",
    "Codegua",
    "Machalí",
    "Olivar",
    "Requinoa",
    "Rengo",
    "Malloa",
    "Quinta de Tilcoco",
    "San Vicente",
    "Pichidegua",
    "Peumo",
    "Coltauco",
    "Coinco",
    "Doñihue",
    "Las Cabras",
    "San Fernando",
    "Chimbarongo",
    "Placilla",
    "Nancagua",
    "Chépica",
    "Santa Cruz",
    "Lolol",
    "Pumanque",
    "Palmilla",
    "Peralillo",
    "Pichilemu",
    "Navidad",
    "Litueche",
    "La Estrella",
    "Marchihue",
    "Paredones",
  ],

  "VII del Maule": [
    "Curicó",
    "Teno",
    "Romeral",
    "Molina",
    "Sagrada Familia",
    "Hualañé",
    "Licantén",
    "Vichuquén",
    "Rauco",
    "Talca",
    "Pelarco",
    "Río Claro",
    "San Clemente",
    "Maule",
    "San Rafael",
    "Empedrado",
    "Pencahue",
    "Constitución",
    "Curepto",
    "Linares",
    "Yerbas Buenas",
    "Colbún",
    "Longaví",
    "Parral",
    "Retiro",
    "Villa Alegre",
    "San Javier",
    "Cauquenes",
    "Pelluhue",
    "Chanco",
  ],

  "VIII del Biobío": [
    // Ñuble (provincia)
    "Chillán",
    "San Carlos",
    "Ñiquén",
    "San Fabián",
    "Coihueco",
    "Pinto",
    "San Ignacio",
    "El Carmen",
    "Yungay",
    "Pemuco",
    "Bulnes",
    "Quillón",
    "Ránquil",
    "Portezuelo",
    "Coelemu",
    "Treguaco",
    "Cobquecura",
    "Quirihue",
    "Ninhue",
    "San Nicolás",
    "Chillán Viejo",

    // Biobío (provincia)
    "Alto Biobío",
    "Los Angeles",
    "Cabrero",
    "Tucapel",
    "Antuco",
    "Quilleco",
    "Santa Bárbara",
    "Quilaco",
    "Mulchén",
    "Negrete",
    "Nacimiento",
    "Laja",
    "San Rosendo",
    "Yumbel",

    // Concepción (provincia)
    "Concepción",
    "Talcahuano",
    "Penco",
    "Tomé",
    "Florida",
    "Hualpén",
    "Hualqui",
    "Santa Juana",
    "Lota",
    "Coronel",
    "San Pedro de la Paz",
    "Chiguayante",

    // Arauco (provincia)
    "Lebu",
    "Arauco",
    "Curanilahue",
    "Los Alamos",
    "Cañete",
    "Contulmo",
    "Tirua",
  ],

  "IX de la Araucanía": [
    // Malleco
    "Angol",
    "Renaico",
    "Collipulli",
    "Lonquimay",
    "Curacautín",
    "Ercilla",
    "Victoria",
    "Traiguén",
    "Lumaco",
    "Purén",
    "Los Sauces",

    // Cautín
    "Temuco",
    "Lautaro",
    "Perquenco",
    "Vilcún",
    "Cholchol",
    "Cunco",
    "Melipeuco",
    "Curarrehue",
    "Pucón",
    "Villarrica",
    "Freire",
    "Pitrufquén",
    "Gorbea",
    "Loncoche",
    "Toltén",
    "Teodoro Schmidt",
    "Saavedra",
    "Carahue",
    "Nueva Imperial",
    "Galvarino",
    "Padre las Casas",
  ],

  "XIV de los Ríos": [
    // Valdivia (provincia)
    "Valdivia",
    "Mariquina",
    "Lanco",
    "Máfil",
    "Corral",
    "Los Lagos",
    "Panguipulli",
    "Paillaco",

    // Ranco (provincia)
    "La Unión",
    "Futrono",
    "Río Bueno",
    "Lago Ranco",
  ],

  "X de los Lagos": [
    // Osorno
    "Osorno",
    "San Pablo",
    "Puyehue",
    "Puerto Octay",
    "Purranque",
    "Río Negro",
    "San Juan de la Costa",

    // Llanquihue
    "Puerto Montt",
    "Puerto Varas",
    "Cochamó",
    "Calbuco",
    "Maullín",
    "Los Muermos",
    "Fresia",
    "Llanquihue",
    "Frutillar",

    // Chiloé
    "Castro",
    "Ancud",
    "Quemchi",
    "Dalcahue",
    "Curaco de Vélez",
    "Quinchao",
    "Puqueldón",
    "Chonchi",
    "Queilén",
    "Quellón",

    // Palena
    "Chaitén",
    "Hualaihué",
    "Futaleufú",
    "Palena",
  ],

  "XI Aysén del General Carlos Ibáñez del Campo": [
    // Coihaique
    "Coyhaique",
    "Lago Verde",

    // Aisén
    "Aysén",
    "Cisnes",
    "Guaitecas",

    // General Carrera
    "Chile Chico",
    "Río Ibánez",

    // Capitán Prat
    "Cochrane",
    "O'Higgins",
    "Tortel",
  ],

  "XII de Magallanes y Antártica Chilena": [
    // Última Esperanza
    "Natales",
    "Torres del Paine",

    // Magallanes
    "Punta Arenas",
    "Río Verde",
    "Laguna Blanca",
    "San Gregorio",

    // Tierra del Fuego
    "Porvenir",
    "Primavera",
    "Timaukel",

    // Antártica Chilena
    "Cabo de Hornos",
    "Antártica",
  ],

  "Metropolitana de Santiago": [
    // Provincia de Santiago
    "Santiago",
    "Independencia",
    "Conchalí",
    "Huechuraba",
    "Recoleta",
    "Providencia",
    "Vitacura",
    "Lo Barnechea",
    "Las Condes",
    "Ñuñoa",
    "La Reina",
    "Macul",
    "Peñalolén",
    "La Florida",
    "San Joaquín",
    "La Granja",
    "La Pintana",
    "San Ramón",
    "San Miguel",
    "La Cisterna",
    "El Bosque",
    "Pedro Aguirre Cerda",
    "Lo Espejo",
    "Estación Central",
    "Cerrillos",
    "Maipú",
    "Quinta Normal",
    "Lo Prado",
    "Pudahuel",
    "Cerro Navia",
    "Renca",
    "Quilicura",

    // Chacabuco
    "Colina",
    "Lampa",
    "Tiltil",

    // Cordillera
    "Puente Alto",
    "San José de Maipo",
    "Pirque",

    // Maipo
    "San Bernardo",
    "Buin",
    "Paine",
    "Calera de Tango",

    // Melipilla
    "Melipilla",
    "María Pinto",
    "Curacaví",
    "Alhué",
    "San Pedro",

    // Talagante
    "Talagante",
    "Peñaflor",
    "Isla de Maipo",
    "El Monte",
    "Padre Hurtado",
  ],
};

// Lista de regiones para el <select> de Región
export const REGIONES = Object.keys(REGIONES_COMUNAS);
